In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to /Users/sr7037/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sr7037/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/sr7037/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
def sort_movies_by_year(li):
    def merge_sort(a,l,r):
        if l==r:
            return
        mid=(l+r)//2
        merge_sort(a,l,mid)
        merge_sort(a,mid+1,r)
        merge(a,l,mid,r)

    def merge(a,l,mid,r):
        n1=mid-l+1
        n2=r-(mid+1)+1
        L=[a[i+l] for i in range(n1)]
        R=[a[i+mid+1] for i in range(n2)]
        i,j,k=0,0,l
        while(i<n1 and j<n2):
            if int(L[i][-5:-1])>int(R[j][-5:-1]) :
                a[k]=L[i]
                i+=1
            else:
                a[k]=R[j]
                j+=1
            k+=1
        while(i<n1):
            a[k]=L[i]
            i+=1
            k+=1
        while(j<n2):
            a[k]=R[j]
            j+=1
            k+=1
    merge_sort(li,0,len(li)-1)

In [3]:
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")
dataset = movies.merge(ratings)
dataset = dataset.loc[:,["userId","movieId","title","genres","rating"]]
df_ratings = dataset.loc[:,["title","rating"]].groupby("title").mean()
genres = dataset["genres"]

In [4]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
li = []
for i in range(len(genres)):
    temp = genres[i].split("|")
    for j in range(len(temp)):
        temp[j] = lemmatizer.lemmatize(temp[j])
    li.append(" ".join(temp))

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(li).toarray()

genres = pd.DataFrame(X,columns=cv.get_feature_names())
dataset = dataset.iloc[:,:-2]
new_dataset = dataset.join(genres)

In [6]:
new_dataset

,userId,movieId,title,action,adventure,animation,children,comedy,crime,documentary,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
0,2,1,Toy Story (1995),0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5,1,Toy Story (1995),0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,8,1,Toy Story (1995),0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,11,1,Toy Story (1995),0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,14,1,Toy Story (1995),0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105334,475,148238,A Very Murray Christmas (2015),0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
105335,458,148626,The Big Short (2015),0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105336,576,148626,The Big Short (2015),0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105337,668,148626,The Big Short (2015),0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105338,475,149532,Marco Polo: One Hundred Eyes (2015),0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

In [6]:
users = new_dataset.drop(["movieId","title"],axis=1)
users_moviemat = users.groupby("userId").sum()
X = users_moviemat.iloc[:,:].values
users_moviemat

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,fi,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
userId,,,,,,,,,,,,,,,,,,,,,
1,46,31,2,3,31,31,1,45,8,25,...,0,1,13,0,2,16,25,43,10,1
2,9,10,2,3,11,3,0,11,4,5,...,0,2,2,0,0,8,5,12,0,0
3,13,9,2,5,35,12,1,36,5,3,...,0,3,4,0,0,22,3,21,3,3
4,14,17,4,6,46,18,0,76,8,3,...,0,6,10,0,6,37,3,18,16,5
5,17,22,21,21,45,6,0,19,16,6,...,0,11,3,0,0,21,6,11,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,36,30,2,3,26,9,1,16,8,22,...,0,6,5,0,0,20,22,22,7,0
665,73,51,7,16,60,61,0,128,25,25,...,0,5,24,0,0,31,25,102,17,5
666,34,27,10,19,83,36,1,101,19,30,...,0,2,20,0,7,26,30,51,8,4
667,16,13,3,3,37,12,0,37,10,7,...,0,1,12,0,0,20,7,17,3,0
668,880,615,122,183,1528,955,160,3329,317,453,...,3,231,464,3,184,1027,453,1491,337,173

In [7]:
from sklearn.neighbors import NearestNeighbors

classifier = NearestNeighbors()
classifier.fit(X)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [10]:
uid = int(input("Enter User Id "))
li = classifier.kneighbors([X[uid-1]],n_neighbors=5,return_distance=False)
current_user = new_dataset.loc[new_dataset["userId"]==li[0][0],:]["title"].values
similar_user = new_dataset.loc[new_dataset["userId"]==li[0][1],:]["title"].values
movies_list = [movie for movie in similar_user if movie not in current_user]
sort_movies_by_year(movies_list)
for i in range(len(movies_list)):
    movies_list[i] = (movies_list[i], df_ratings['rating'][df_ratings.index == movies_list[i]].values[0])
print("Recommended Movies are: ")
movies_list

Enter User Id 108
Recommended Movies are:

[('Harry Potter and the Deathly Hallows: Part 1 (2010)', 3.7580645161290325),
 ('Black Swan (2010)', 3.9655172413793105),
 ('Devil (2010)', 3.0714285714285716),
 ('Easy A (2010)', 3.3461538461538463),
 ('Social Network, The (2010)', 3.875),
 ('Machete (2010)', 3.3636363636363638),
 ('Scott Pilgrim vs. the World (2010)', 4.0),
 ('Expendables, The (2010)', 3.125),
 ('Salt (2010)', 3.3125),
 ('Karate Kid, The (2010)', 3.3333333333333335),
 ('Inception (2010)', 4.189320388349515),
 ('Toy Story 3 (2010)', 4.142857142857143),
 ('Get Him to the Greek (2010)', 3.15),
 ('Iron Man 2 (2010)', 3.6451612903225805),
 ('Death at a Funeral (2010)', 2.75),
 ('Kick-Ass (2010)', 3.857142857142857),
 ('How to Train Your Dragon (2010)', 3.757142857142857),
 ("She's Out of My League (2010)", 3.0),
 ("Valentine's Day (2010)", 3.0),
 ('Avatar (2009)', 3.856060606060606),
 ('Invictus (2009)', 3.5833333333333335),
 ('Blind Side, The  (2009)', 3.9347826086956523),
 ('Ninja Assassin (2009)', 3.2857142857142856),
 ('Fantastic Mr. Fox (2009)', 4.0),
 ('Up in the Air (2009)', 3.92),
 ('Zombieland (2009)', 3.765957446808511),
 ('Men Who Stare at Goats, The (2009)', 3.1785714285714284),
 ('Julie & Julia (2009)', 3.7222222222222223),
 ('(500) Days of Summer (2009)', 3.9324324324324325),
 ('Hangover, The (2009)', 3.705357142857143),
 ('Up (2009)', 4.153225806451613),
 ('X-Men Origins: Wolverine (2009)', 3.3214285714285716),
 ('Moon (2009)', 4.0625),
 ('Crank: High Voltage (2009)', 2.0),
 ('17 Again (2009)', 2.875),
 ('Observe and Report (2009)', 2.5714285714285716),
 ('I Love You, Man (2009)', 3.5357142857142856),
 ('Funny People (2009)', 3.5),
 ("He's Just Not That Into You (2009)", 3.1666666666666665),
 ('Watchmen (2009)', 3.8020833333333335),
 ("Dr. Horrible's Sing-Along Blog (2008)", 4.434782608695652),
 ('Marley & Me (2008)', 3.5),
 ('Curious Case of Benjamin Button, The (2008)', 3.725806451612903),
 ('Gran Torino (2008)', 3.9680851063829787),
 ('Slumdog Millionaire (2008)', 3.9357142857142855),
 ('Zack and Miri Make a Porno (2008)', 3.357142857142857),
 ("Nick and Norah's Infinite Playlist (2008)", 3.6666666666666665),
 ('How to Lose Friends & Alienate People (2008)', 3.625),
 ('Eagle Eye (2008)', 2.95),
 ('Step Brothers (2008)', 3.1153846153846154),
 ('Wanted (2008)', 3.176470588235294),
 ('Incredible Hulk, The (2008)', 3.4285714285714284),
 ('Taken (2008)', 3.8444444444444446),
 ('Iron Man (2008)', 3.89375),
 ('Forgetting Sarah Marshall (2008)', 3.8333333333333335),
 ('Dark Knight, The (2008)', 4.141732283464567),
 ('Run Fatboy Run (2007)', 3.4),
 ('Juno (2007)', 3.6746031746031744),
 ('Superbad (2007)', 3.8444444444444446),
 ('Bourne Ultimatum, The (2007)', 3.8642857142857143),
 ('Simpsons Movie, The (2007)', 3.5972222222222223),
 ('Fantastic Four: Rise of the Silver Surfer (2007)', 2.4615384615384617),
 ('Knocked Up (2007)', 3.6129032258064515),
 ('Spider-Man 3 (2007)', 2.8),
 ('Sunshine (2007)', 3.5),
 ('Grindhouse (2007)', 3.9),
 ('300 (2007)', 3.5779220779220777),
 ('Ghost Rider (2007)', 2.6666666666666665),
 ('Epic Movie (2007)', 1.5),
 ('Black Snake Moan (2006)', 3.125),
 ('Blood Diamond (2006)', 3.7777777777777777),
 ('Casino Royale (2006)', 3.89375),
 ('Children of Men (2006)', 3.9827586206896552),
 ('Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan (2006)',
  3.875),
 ('Illusionist, The (2006)', 3.77027027027027),
 ('Crank (2006)', 3.2777777777777777),
 ('Pursuit of Happyness, The (2006)', 3.8043478260869565),
 ('Talladega Nights: The Ballad of Ricky Bobby (2006)', 3.125),
 ('Babel (2006)', 3.5454545454545454),
 ('Little Miss Sunshine (2006)', 4.078947368421052),
 ('Devil Wears Prada, The (2006)', 3.210526315789474),
 ('X-Men: The Last Stand (2006)', 3.1666666666666665),
 ('Mission: Impossible III (2006)', 3.3095238095238093),
 ('Thank You for Smoking (2006)', 3.826530612244898),
 ('V for Vendetta (2006)', 4.01595744680851),
 ('Protector, The (a.k.a. Warrior King) (Tom yum goong) (2005)', 3.875),
 ('40-Year-Old Virgin, The (2005)', 3.6847826086956523),
 ('Mr. & Mrs. Smith (2005)', 3.05),
 ('Sin City (2005)', 3.91875),
 ('Hitch (2005)', 3.5),
 ('Are We There Yet? (2005)', 0.75),
 ('Elektra (2005)', 2.4444444444444446),
 ('Crash (2004)', 3.5625),
 ('Incredibles, The (2004)', 3.926470588235294),
 ('Garden State (2004)', 3.6702127659574466),
 ('Spider-Man 2 (2004)', 3.553030303030303),
 ('Notebook, The (2004)', 4.142857142857143),
 ('Dodgeball: A True Underdog Story (2004)', 3.5833333333333335),
 ('Mean Girls (2004)', 3.6153846153846154),
 ('Kill Bill: Vol. 2 (2004)', 3.9615384615384617),
 ('Ladykillers, The (2004)', 3.1),
 ('Eternal Sunshine of the Spotless Mind (2004)', 4.122448979591836),
 ('Girl Next Door, The (2004)', 3.65),
 ('EuroTrip (2004)', 3.3333333333333335),
 ('50 First Dates (2004)', 3.3684210526315788),
 ('Lord of the Rings: The Return of the King, The (2003)', 4.108433734939759),
 ('Love Actually (2003)', 3.9204545454545454),
 ('Matrix Revolutions, The (2003)', 3.1746031746031744),
 ('Kill Bill: Vol. 1 (2003)', 3.977272727272727),
 ('American Wedding (American Pie 3) (2003)', 2.65),
 ('Pirates of the Caribbean: The Curse of the Black Pearl (2003)',
  3.8297872340425534),
 ('Swimming Pool (2003)', 3.642857142857143),
 ('Terminator 3: Rise of the Machines (2003)', 3.0652173913043477),
 ('Hulk (2003)', 2.859375),
 ('Finding Nemo (2003)', 3.888888888888889),
 ('Matrix Reloaded, The (2003)', 3.29375),
 ('X2: X-Men United (2003)', 3.567073170731707),
 ('Anger Management (2003)', 2.7),
 ('Daredevil (2003)', 2.5166666666666666),
 ('How to Lose a Guy in 10 Days (2003)', 3.175),
 ('Catch Me If You Can (2002)', 4.0),
 ('Two Weeks Notice (2002)', 3.107142857142857),
 ('Lord of the Rings: The Two Towers, The (2002)', 4.095808383233533),
 ('Adaptation (2002)', 3.9761904761904763),
 ('Ring, The (2002)', 3.3863636363636362),
 ('Transporter, The (2002)', 3.4791666666666665),
 ('Minority Report (2002)', 3.685185185185185),
 ('Bourne Identity, The (2002)', 3.893805309734513),
 ('Spider-Man (2002)', 3.5098039215686274),
 ('Beautiful Mind, A (2001)', 3.9952380952380953),
 ('Lord of the Rings: The Fellowship of the Ring, The (2001)',
  4.126984126984127),
 ('Royal Tenenbaums, The (2001)', 3.8636363636363638),
 ("Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)", 4.07563025210084),
 ("Ocean's Eleven (2001)", 3.7436974789915967),
 ('Monsters, Inc. (2001)', 3.8793103448275863),
 ('Serendipity (2001)', 3.607142857142857),
 ('American Pie 2 (2001)', 2.988095238095238),
 ('Swordfish (2001)', 3.0833333333333335),
 ('Shrek (2001)', 3.7563291139240507),
 ('Memento (2000)', 4.0576923076923075),
 ('O Brother, Where Art Thou? (2000)', 3.9510869565217392),
 ('Cast Away (2000)', 3.717171717171717),
 ('Snatch (2000)', 4.073863636363637),
 ('Crouching Tiger, Hidden Dragon (Wo hu cang long) (2000)',
  3.9732142857142856),
 ('Almost Famous (2000)', 3.8855421686746987),
 ('X-Men (2000)', 3.5576923076923075),
 ('Me, Myself & Irene (2000)', 3.039473684210526),
 ('Mission: Impossible II (2000)', 2.7933333333333334),
 ('American Psycho (2000)', 3.7625),
 ('Boondock Saints, The (2000)', 3.9651162790697674),
 ('Deuce Bigalow: Male Gigolo (1999)', 2.8076923076923075),
 ('Toy Story 2 (1999)', 3.9134615384615383),
 ('American Pie (1999)', 3.2663551401869158),
 ('Wild Wild West (1999)', 2.1641791044776117),
 ("You've Got Mail (1998)", 3.3425925925925926),
 ('Waterboy, The (1998)', 2.8653846153846154),
 ('Speed 2: Cruise Control (1997)', 1.7741935483870968),
 ('Jingle All the Way (1996)', 2.75),
 ('Happy Gilmore (1996)', 3.449367088607595),
 ('Clueless (1995)', 3.2755102040816326),
 ('Babe (1995)', 3.616279069767442),
 ('Jumanji (1995)', 3.3532608695652173),
 ('Lion King, The (1994)', 3.7709497206703912),
 ('Clerks (1994)', 3.98019801980198),
 ('Sleepless in Seattle (1993)', 3.5236220472440944),
 ("Schindler's List (1993)", 4.296370967741935),
 ('Mrs. Doubtfire (1993)', 3.3283132530120483),
 ('Last Action Hero (1993)', 2.883116883116883),
 ('Home Alone (1990)', 3.032258064516129),
 ("Monty Python's The Meaning of Life (1983)", 3.9239130434782608),
 ('Young Frankenstein (1974)', 4.013888888888889),
 ('Willy Wonka & the Chocolate Factory (1971)', 3.786764705882353),
 ('Sound of Music, The (1965)', 3.9655172413793105),
 ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)',
  4.116),
 ("Breakfast at Tiffany's (1961)", 3.9390243902439024),
 ('Casablanca (1942)', 4.236)]